@startuml
hide footbox
title AddCommand

participant "command:AddCommand" as AddCommand
participant "tasklist:TaskList" as TaskList
participant "task:Task" as Task


->AddCommand: execute()
activate AddCommand
AddCommand->TaskList: addTask()
activate TaskList

TaskList->TaskList: addTask()

TaskList->TaskList: createTask()
activate TaskList
create Task
TaskList->Task:
activate Task
return task
TaskList-->TaskList: task
deactivate TaskList

TaskList->TaskList: checkClash()
activate TaskList
return boolean
TaskList->TaskList: updateMaxNumber()
activate TaskList
return
TaskList-->AddCommand:
deactivate TaskList
<--AddCommand--



@enduml