@startuml
hide footbox
title DeleteCommand
participant "command:DeleteCommand" as DeleteCommand
participant "tasklist:TaskList" as TaskList
participant "task:Task" as Task
participant "athenaUi:ATHENAUI" as AthenaUI

->DeleteCommand: execute()
activate DeleteCommand
DeleteCommand->TaskList: deleteTask()
activate TaskList
TaskList->Task**
activate Task
return task
return task
DeleteCommand->Task++:getTaskRestore()
return String
DeleteCommand->AthenaUI++: printTaskDeleted()
AthenaUI->Task++:getName()
return String
AthenaUI-->DeleteCommand--:
<--DeleteCommand:


@enduml