@startuml
hide footbox
title Edit

participant "command:EditCommand" as EditCommand
participant "tasklist:TaskList" as TaskList
participant "task:Task" as Task

->EditCommand++: execute()
EditCommand->TaskList++: editTask()
TaskList->TaskList++: createTask()
TaskList->Task**:
activate Task
Task-->TaskList--
TaskList->Task++: edit()
Task-->TaskList--:
return task
TaskList-->EditCommand--:
<--EditCommand

@enduml