@startuml
title List
hide footbox
->ListCommand++: execute()
ListCommand->Timetable**:
activate Timetable
Timetable->ImportanceFilter++
return
Timetable->ForecastFilter++
destroy ImportanceFilter
return
return Timetable
destroy ForecastFilter

ListCommand->AthenaUI++: printTimetable()
AthenaUI-->ListCommand--:

<--ListCommand--
@enduml