@startuml
title LOAD
hide footbox


->Storage++: loadTaskListData()
Storage->TaskList**:
activate TaskList
Storage->File**
loop csvReader.readLine()
    Storage->TaskList: addTask()
    TaskList-->Storage
end
return taskList
return taskList
@enduml