@startuml
title Save
participant "storage:Storage" as Storage
participant ":Time" as Time
participant ":Task" as Task
participant ":TaskList" as TaskList
participant ":File" as File

->Storage++: saveTaskListData()
Storage->TaskList++: getTasks()
return
loop nextTask
Storage->Task++: getTimeInfo()
Task->Time**
activate Time
return Time
return Time
Storage->Task++: getName()
return
Storage->Time++:getStartTimeString()
return
Storage->Time++: getDurationString()
return
Storage->Time++:getDeadline()
return
Storage->Time++:getRecurrence()
return
Storage->Task++: getImportance()
return
Storage->Task++: getNotes()
return
Storage->Task++: getNumber()
return
Storage->Task++: isDone()
return
Storage->Task++: isFlexible()
return
end
<--Storage--
@enduml